Trie0037/Afterclass

client/src/components/Project/Project.js
client/src/components/Title/Title.js
client/src/pages/dashboard/Dashboard.js
client/src/utils/pitchApi.js
controllers/pitch.js
server.js

-Adding in the Title component requires the project id to be passed in as a key
-More renaming of variable names

more renaming, fixed console issue with id's

---

controllers/pitch.js
models/pitch.js

-Projects are sorted from most recent by date

sort projects list from newest to oldest by date

---

client/src/components/Project/Project.js
client/src/pages/dashboard/Dashboard.js
client/src/utils/pitchApi.js
controllers/pitch.js
server.js

-Add mongo query to check if the user voted on the current project
-Make a check to see if the user has voted on the project before performing an upvote or downvote

users can only vote once on each project

---

client/src/components/Jumbotron/Jumbotron.js
client/src/pages/Login/Login.js

jumbo style

---

client/src/pages/dashboard/Dashboard.js

Added features to validate form submit.

form submit validation

---

client/src/pages/dashboard/Dashboard.js

-Removed unnecessary code and formatting.
-Removed those two handleChange functions to use just one. We will use this one for now on.

removed unnecessary code, formatting

---

client/src/App.css
client/src/components/DeleteBtn/DeleteBtn.js
client/src/pages/SignUp/SignUp.js

Fixed Signup button and edited app.css

button fix

---

client/src/App.css
server.js

adding sleeper interval

---

client/src/pages/Home/Home.js
client/src/pages/dashboard/Dashboard.js
client/src/utils/pitchApi.js
controllers/pitch.js
models/pitch.js
server.js

Checking index for production.

mongo index check

---

client/src/components/UserProject/UserProject.js
client/src/components/UserProject/index.js
client/src/pages/dashboard/Dashboard.js

User projects for a single user now rendering.

added user projects

---

client/src/App.css
client/src/components/Project/Project.js
client/src/components/UserProject/UserProject.js
client/src/pages/dashboard/Dashboard.js
server.js

-Formatted date for projects
-When a user has not created a project, a text will appear in the Your Project section letting them know.

formatted date, add ternary to check userProjects

---

client/src/pages/Dashboard/Dashboard.js
client/src/pages/Dashboard/index.js

Naming convention of Dashboard page was not up to React naming convention. Dashboard was named "dashboard" which caused case issues while finally correcting it and deploying the fix. Removed the Dashboard folder completely, but this commit put it back with the correct naming convention.

add Dashboard page, fixing heroku case issue

---

client/src/App.css
client/src/components/UserProject/UserProject.js
client/src/pages/Dashboard/Dashboard.js
client/src/utils/pitchApi.js
controllers/pitch.js
server.js

handleDeleteMyProject button now deletes a userProject.  Still needs some sort of "Are you sure you want to delete?" validation.

handleDeleteBtn

---

client/src/App.css
client/src/pages/Dashboard/Dashboard.js
controllers/pitch.js

Just some small refactoring on a few files.

small refactoring on alerts and formatting

---

client/src/App.css
client/src/components/Card/Card.js
client/src/components/Header/Header.js
client/src/components/ThreeHighestVotedProjects/ThreeHighestVotedProjects.js
client/src/components/ThreeHighestVotedProjects/index.js
client/src/pages/Home/Home.js
client/src/utils/pitchApi.js
controllers/pitch.js
server.js

-Some refactoring on the Home page
-Added new component to render top three voted projects
-Added a placeholder image for the top three voted projects

refactoring on Home, fixed cards, add placeholder image

---

client/src/components/CoursesToJoin/CoursesToJoin.js
client/src/components/CoursesToJoin/index.js
client/src/components/HomePageDetails/HomePageDetails.js
client/src/components/HomePageDetails/index.js
client/src/components/ThreeHighestVotedProjects/ThreeHighestVotedProjects.js
client/src/pages/Dashboard/Dashboard.js
client/src/pages/Home/Home.js

-Created separate components to cleanup Home page
-Removed unused and duplicate imports

more refactoring on Home page, divided into components

---

client/src/App.css
client/src/App.js
client/src/components/Header/Header.js
client/src/pages/About/About.js
client/src/pages/About/index.js
client/src/pages/NoMatch/index.js

Added About page and deleted No Match page.

added about page

---

client/src/App.js
client/src/pages/Dashboard/Dashboard.js
client/src/pages/SignUp/SignUp.js
client/src/utils/pitchApi.js
controllers/pitch.js
models/user.js
server.js

fixed a bug upon signup

---

client/src/pages/About/About.js
client/src/pages/Dashboard/Dashboard.js
client/src/pages/SignUp/SignUp.js
client/src/utils/pitchApi.js
controllers/pitch.js
server.js

-Small refactoring, renamed a few endpoints and functions. Old name for saving a project made me wanna throw up.

small refactoring on backend and frontend

---

client/src/App.js
client/src/components/AllProjects/AllProjects.js
client/src/components/AllProjects/index.js
client/src/components/HeaderLoggedIn/HeaderLoggedIn.js
client/src/components/HeaderLoggedOut/HeaderLoggedOut.js
client/src/pages/Projects/Projects.js
client/src/pages/Projects/index.js

Added projects page with all submitted projects.

projects submitted page

---

client/src/App.css
client/src/App.js
client/src/components/UserProject/UserProject.js
client/src/pages/Dashboard/Dashboard.js
client/src/pages/EditOneProject/EditProject.js
client/src/pages/EditOneProject/index.js
client/src/utils/pitchApi.js
controllers/pitch.js
server.js

edit features

---

client/src/App.js
client/src/assets/Defaults.js
client/src/assets/index.js
client/src/components/AllProjects/AllProjects.js
client/src/components/UserProject/UserProject.js
client/src/pages/Dashboard/Dashboard.js
client/src/pages/EditOneProject/EditProject.js
client/src/utils/pitchApi.js
controllers/pitch.js
server.js

-Enabling the edit feature to edit one project.
-Add extra validation when submitting an edited project, if the image input is blank or empty, the default image will save to the database.
-Create a new Defaults page to store the default values, like our default image.
-Change the default image to the React image from this repo.
-Removed some unnecessary code, some refactoring.

enabling edit one project feature, some refactoring

---

client/src/components/HomePageDetails/HomePageDetails.js
client/src/pages/About/About.js

-Reallocated home page goals/paragraphs to about page.
-Edited paragraphs.

about page

---

client/src/App.js
client/src/components/ThreeHighestVotedProjects/ThreeHighestVotedProjects.js
client/src/pages/DisplayProjectDetails/DisplayProjectDetails.js
client/src/pages/DisplayProjectDetails/index.js
client/src/pages/Home/Home.js
client/src/utils/pitchApi.js
controllers/pitch.js
models/pitch.js
server.js

-Added route from home page to display project details page.
-Enabled logged in user to submit interested project.
-Added project details page.

added join project details

---

client/src/App.js
client/src/components/AllProjects/AllProjects.js
client/src/pages/Dashboard/Dashboard.js
client/src/pages/DisplayProjectDetails/DisplayProjectDetails.js
client/src/pages/EditOneProject/EditProject.js
client/src/pages/Projects/Projects.js
client/src/utils/pitchApi.js
controllers/pitch.js
server.js

-Add validation to Email field when submitting a new interest on a project
-Projects are also clickable via the Project page
-Project Details page now showing how many interest submissions
-Some refactoring and formatting

Validation and Clickable Projects

---

client/src/App.css
client/src/components/InterestedUserSubmissions/InterestedUserSubmissions.js
client/src/components/InterestedUserSubmissions/index.js
client/src/pages/DisplayProjectDetails/DisplayProjectDetails.js
models/pitch.js

-Add new component to render the email and comments from interested users
-The full email of the users will only display for logged in users. If the user is logged out, only the first 3 letters of the email displays.

add feature to see interested user results

---

client/src/App.js
client/src/components/AllProjects/AllProjects.js
client/src/components/InterestedUserSubmissions/InterestedUserSubmissions.js
client/src/components/ThreeHighestVotedProjects/ThreeHighestVotedProjects.js
client/src/pages/DisplayProjectDetails/DisplayProjectDetails.js
client/src/pages/Home/Home.js
client/src/pages/Projects/Projects.js
client/src/pages/SignUp/SignUp.js
controllers/pitch.js

-For users on prod who do not have emails, their username will display when they submit a comment on a project
-Some refactoring, there is much more to do as there are a lot of unused/unnecessary code

add condition to display username if email DNE

---

client/src/App.css
client/src/components/Form/FormBtn.js
client/src/pages/Dashboard/Dashboard.js
client/src/pages/DisplayProjectDetails/DisplayProjectDetails.js
client/src/pages/EditOneProject/EditProject.js
client/src/pages/Login/Login.js
client/src/pages/SignUp/SignUp.js

-Adjusted edit/delete buttons
-Adjusted upvote/downvote buttons
-Centered login/signup page button
-still need to update display project details buttons ( logged in join project page )

button adjustments

---

client/src/App.css
client/src/components/Project/Project.js

Adjusted project columns and added breakWord to CSS to prevent column overflow.

adjusting project columns

---

client/src/components/Project/Project.js
client/src/components/UserProject/UserProject.js

Edit and Delete Buttons refactored to match Upvote/Downvote Buttons.
User Project Title, Description, Votes, and Formatted Date columns refactored.

edit delete column rows

---

client/src/App.css
client/src/components/Form/FormBtn.js
client/src/pages/Dashboard/Dashboard.js

Created new row and column for dashboard submit button.
Added style.

loosen up some buttons

---

client/src/pages/SignUp/SignUp.js

Added input validation upon signup.
i.e. 6 characters, @email, elimination of spaces in username field

form validation upon signup

---

client/src/App.css
client/src/pages/Settings/Settings.js
client/src/utils/pitchApi.js
controllers/projectController.js
server.js

- Add feature to reset background image to default
- Other small front end changes

add feature to reset background image
